### ISSUE TITLE
Navigation with IMU

### ISSUE THREAD

**Issue by ozgetuncer** [xioTechnologies/Gait-Tracking-With-x-IMU#10]
I am using another IMU sensor with 3-axis magnetometer, 3-axis gyroscope and 3-axis accelerometer and want to do dead reckoning. Different than your project, I am carrying the sensor by hand so that I haven't got the effect of hitting the ground. Can I use your source code directly for this scenario or is there any way to adapt?

**Comment by xioTechnologies** [comment]
This demo is for an IMU attached to the foot.  I do not have any resources for share for the scenario you have described.
