### ISSUE TITLE
IMU data drifting

### ISSUE THREAD

**Issue by wippp** [xioTechnologies/Gait-Tracking-With-x-IMU#13]
Hi!

I was very impressed with your work with the Gait tracking algorithm and wanted to test it with my MPU-9250 sensor. I strapped the sensor onto my ankle and walked on a treadmill while sampling data. I then managed to feed my data into your Matlab script and got a result but the output drifts several meters.
I will include a picture of the output and perhaps someone could help me figure out what I am doing wrong...

Best Regards
Anders Persson
![test7](https://user-images.githubusercontent.com/25609019/38366919-8c55cfc2-38e1-11e8-8cfc-05dea3d763f9.jpg)

**Comment by xioTechnologies** [comment]
The IMU must be attached to the foot, not the ankle.  A sensor attached to the ankle will never be stationary; this is a fundamental requirement of the algorithm.  The algorithm will not work with a treadmill for the same reason.

**Comment by wippp** [comment]
Thank you for answer! I realised that also after a while.... Did some test with an IMU attached to the foot resiliently with much better results.
