### ISSUE TITLE
How to get the packet number??

### ISSUE THREAD

**Issue by vetridevilla** [xioTechnologies/Gait-Tracking-With-x-IMU#15]
i am using sparkfun imu 9250 in arduino. i can get the accelerometer (g) and gyro (dps) values. i set the sample rate at 256 and low pass filter at 42. 

 where will i get packet number? if it is any code is there for the packet number please share. I am a beginner if anything wrong please suggest the right way

Thank you

**Comment by xioTechnologies** [comment]
The packet number is not used by the code.
