### ISSUE TITLE
Not x-IMU issue, just personal question

### ISSUE THREAD

**Issue by Odor98** [xioTechnologies/Gait-Tracking-With-x-IMU#17]
I'm a student

I want to measure the moving distance of a car.
simple distance data is enough

My question is 
1. is there an answer to ( 3-axis accelerator + gyro ) data processing code?
2. I watch x-IMU video,            ㄴ Matlab was used to process the data, Matlab is necessary?
3. what kind of language that x-imu project?

**Comment by xioTechnologies** [comment]
This foot tracking example would not be applicable to a car.  I doubt you will be able to achieve reliable tracking using IMU technology alone.
