### ISSUE TITLE
Hi,thanks for your code

### ISSUE THREAD

**Issue by arcgislearner** [xioTechnologies/Gait-Tracking-With-x-IMU#26]

**Comment by arcgislearner** [comment]
Hello,
  Thank you very much for your code,there is  two  question:
  How can i get the bin file? i just get the data in csv format. And i doesn't have the packagenumber, Does this affect my experiment?

Best wishes
Jiahao Chen

**Comment by xioTechnologies** [comment]
The .bin is not used, neither is packet number.

**Comment by arcgislearner** [comment]
Ok, I see. Thank you for your reply.&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"x-io Technologies"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月28日(星期一) 晚上9:06
收件人:&nbsp;"xioTechnologies/Gait-Tracking-With-x-IMU"<Gait-Tracking-With-x-IMU@noreply.github.com&gt;;
抄送:&nbsp;"philrain"<cjh19970707@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xioTechnologies/Gait-Tracking-With-x-IMU] Hi,thanks for your code (#26)




The .bin is not used, neither is packet number.
