### ISSUE TITLE
What type of binary files are being read in the datasets

### ISSUE THREAD

**Issue by kswain1** [xioTechnologies/Gait-Tracking-With-x-IMU#4]
Currently have my data in csv format, but I don't understand how to convert it into .BIN format for it to be read by the matlab program. Is there any way around this issue?

Ok I was able to get the file to be read into program, but currently I am having a problem with the raw data being loaded on the plotter. Current error file looks like this 
-Warning: Plot empty. 

> In legend (line 260)
>   In Script (line 89) 
> Warning: Plot empty. 
> In legend (line 260)
>   In Script (line 101) 
> Index exceeds matrix dimensions.

Error in Script (line 113)
indexSel = 1 : find(sign(time-(time(1)+initPeriod))+1, 1);

Has anyone encountered such error logs?

**Comment by ybcho** [comment]
I really hope to know how I can change my own .CSV file to .BIN file...plz help me...

**Comment by debajyoti93** [comment]
Facing the same issue. Please help me

**Comment by VagabundoPL** [comment]
make sure, that your initPeriod value is not bigger than the last value of paket number in input file.

**Comment by ozgetuncer** [comment]
I have also have the .csv file and need to .bin file. How did you able to read the data?

**Comment by xioTechnologies** [comment]
The x-IMU logs data to the SD card as a .bin file.  The .bin file can then be converted to CSV files using the x-IMU GUI.  The .bin is not used by the MATLAB script.

**Comment by MuhammadAli152** [comment]
I am getting the following error.

Index exceeds matrix dimensions.

Error in Script (line 109)
indexSel = 1 : find(sign(time-(time(1)+initPeriod))+1, 1);

Please Help me in this regard Thank You.

**Comment by Wangkingling** [comment]
> 我犯了以下错误。
> 
> 索引超过矩阵维度。
> 
> 脚本错误（行 109）
> 索引塞尔 = 1 ： 查找 （符号 （时间 -（1）=initPeriod）=1，1）：
> 
> 请在这方面帮助我谢谢。

    % Compute integral drift during non-stationary periods
    velDrift = zeros(size(vel));
    stationaryStart = find([0; diff(stationary)] == -1);
    stationaryEnd = find([0; diff(stationary)] == 1);
    if length(stationaryStart) ~= length(stationaryEnd)
        for i = 1:numel(stationaryEnd)-1
            driftRate = vel(stationaryEnd(i)-1, :) / (stationaryEnd(i) - stationaryStart(i));
            enum = 1:(stationaryEnd(i) - stationaryStart(i));
            drift = [enum'*driftRate(1) enum'*driftRate(2) enum'*driftRate(3)];
            velDrift(stationaryStart(i):stationaryEnd(i)-1, :) = drift;
        end
    else
        for i = 1:numel(stationaryEnd)
            driftRate = vel(stationaryEnd(i)-1, :) / (stationaryEnd(i) - stationaryStart(i));
            enum = 1:(stationaryEnd(i) - stationaryStart(i));
            drift = [enum'*driftRate(1) enum'*driftRate(2) enum'*driftRate(3)];
            velDrift(stationaryStart(i):stationaryEnd(i)-1, :) = drift;
        end
    end
