### ISSUE TITLE
error: No data was imported

### ISSUE THREAD

**Issue by ozanAta** [xioTechnologies/Gait-Tracking-With-x-IMU#6]
Hi,
I am new to MATLAB/Octave and currently when i run the Script file on Octave i get the following error

`
error: No data was imported. 
error: called from
    xIMUdataClass at line 49 column 17
    Script at line 26 column 10
`

I am running the exact file on this repository, what do you think the problem could be?

**Comment by weibo053** [comment]
This happens to me as well, please help

**Comment by ozgetuncer** [comment]
I get this error too and need help.

Error using xIMUdataClass (line 49)
No data was imported.

Error in Script (line 26)
xIMUdata = xIMUdataClass(filePath, 'InertialMagneticSampleRate', 1/samplePeriod);

**Comment by xioTechnologies** [comment]
I have just downloaded the repository from GitHub and run the script in MATLAB R2017a without issue. 
 "No data was imported." is an error message created by the x-IMU MATLAB Library.  I suggest you investigate what the source error is.

**Comment by daylanKifky** [comment]
Trying to run it with `octave` does raise the described error.

the error inside the `xIMUdataClass` is:

```
parse error near line 27 of file /home/daylan/X/repos/Gait-Tracking-With-x-IMU/Gait Tracking With x-IMU/ximu_matlab_library/TimeSeriesDataBaseClass.m

  external methods are only allowed in @-folders

>>>         Plot(obj);
