### ISSUE TITLE
Reading in my own CSV file of data

### ISSUE THREAD

**Issue by CarbontTitan** [xioTechnologies/Gait-Tracking-With-x-IMU#7]
I have collected my own data in CSV format, however, how do I get it read into the program?
How do you create the BIN files?
Many thanks.

**Comment by xioTechnologies** [comment]
The BIN file is not used by the MATLAB script.  It is only included for reference.

**Comment by syahrulizmeer** [comment]
then how we want to add our own data?
Much appreciated for the reply
thank you

**Comment by declanxyz** [comment]
seems that we are meeting the same problem.
what we want to know the most is how to run the code using our own data?
really appreciate it if this problem can be solved.

**Comment by xioTechnologies** [comment]
The code is provided with example data and runs without issues.  You can modify the code or the data however you like.  There are no tutorials for this.
